# Generated by Django 3.1 on 2020-09-02 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboracion',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.proyecto'),
        ),
        migrations.AlterField(
            model_name='colaboracion',
            name='id_tipo_permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.tipo_permiso'),
        ),
        migrations.AlterField(
            model_name='colaboracion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.usuario'),
        ),
    ]
