# Generated by Django 3.1 on 2020-09-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20200901_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
