# Generated by Django 3.1 on 2020-09-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_auto_20200903_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_segmento',
            name='descripcion',
            field=models.CharField(default='descript', max_length=500),
            preserve_default=False,
        ),
    ]
