# Generated by Django 3.1 on 2020-09-04 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_tipo_segmento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmento',
            name='numero_segmento',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='tipo_segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.tipo_segmento', unique=True),
        ),
    ]
