# Generated by Django 3.1 on 2020-09-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_auto_20200903_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmento',
            name='tipo_segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.tipo_segmento'),
        ),
    ]
