# Generated by Django 3.1 on 2020-09-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_auto_20200903_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmento',
            name='numero_segmento',
            field=models.IntegerField(default=0),
        ),
    ]
