# Generated by Django 3.1 on 2020-09-07 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0011_auto_20200903_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 16, 37, 28, 493006, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
