# Generated by Django 3.1 on 2020-09-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_perfil_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=200)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.segmento', unique=True)),
            ],
        ),
    ]
