# Generated by Django 3.1 on 2020-09-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0014_videoyt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='texto',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Herramienta_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.herramienta', unique=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.proyecto', unique=True)),
            ],
        ),
    ]
