# Generated by Django 3.1 on 2020-09-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0015_auto_20200916_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta_proyecto',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.herramienta'),
        ),
        migrations.AlterField(
            model_name='herramienta_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.proyecto'),
        ),
    ]
