# Generated by Django 3.1 on 2020-09-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0017_auto_20200916_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='retrato',
            field=models.ImageField(null=True, upload_to='retratos'),
        ),
    ]
