# Generated by Django 3.1 on 2020-09-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0018_auto_20200916_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='alma_mater',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='carrera',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
