# Generated by Django 3.1 on 2020-09-16 23:42

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0019_auto_20200916_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='retrato2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='retratos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='retrato',
            field=models.ImageField(blank=True, null=True, upload_to='retratos'),
        ),
    ]
