# Generated by Django 3.1 on 2020-09-16 23:53

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0020_auto_20200916_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='retrato3',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='path/to/img'),
        ),
    ]
