# Generated by Django 3.1 on 2020-10-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0023_usuario_user_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='reseña',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
