# Generated by Django 3.1 on 2020-10-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0024_proyecto_reseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoyt',
            name='segmento',
        ),
        migrations.AddField(
            model_name='segmento',
            name='titular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='segmento',
            name='var1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='segmento',
            name='var2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='segmento',
            name='var3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='segmento',
            name='var4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='segmento',
            name='var5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Texto',
        ),
        migrations.DeleteModel(
            name='Videoyt',
        ),
    ]
