# Generated by Django 3.1 on 2020-10-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0025_auto_20201013_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmento',
            name='var1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='var2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='var3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='var4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='var5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
