# Generated by Django 3.1 on 2020-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0028_auto_20201017_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='retrato',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
