# Generated by Django 3.1 on 2020-10-18 15:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0029_auto_20201017_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='retrato',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=''),
        ),
    ]
