# Generated by Django 3.1 on 2020-10-18 17:43

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0030_auto_20201018_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='retrato',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
